---
- hosts: all
  roles:
    - geerlingguy.ntp
    - geerlingguy.docker
  vars:
    ntp_timezone: "US/Pacific"
  tasks:
    - name: Install DigitalOcean repo key
      apt_key:
        url: https://repos.sonar.digitalocean.com/sonar-agent.asc
        state: present

    - name: Install DigitalOcean apt repo
      apt_repository:
        repo: deb https://repos.sonar.digitalocean.com/apt main main
        state: present
        update_cache: yes

    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - git
          - mosh
          - zsh
          - do-agent
          - openssh-client
          - direnv
          - keychain

    - name: Add non root user
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
        groups: sudo, docker
        append: yes

    - name: Set authorized key for user copying it from current user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
